package main

import (
	"context"

	"github.com/rs/zerolog/log"
	"github.com/segmentio/kafka-go"
)

func (h *handler) processKafkaMessage() error {
	k := kafka.NewReader(kafka.ReaderConfig{
		Brokers: []string{h.config.KafkaBroker},
		GroupID: "tg-notify-bot",
		GroupTopics: []string{
			"debezium.chii.bangumi.chii_pms",
			"debezium.chii.bangumi.chii_notify",
		},
	})

	for {
		msg, err := k.ReadMessage(context.Background())
		if err != nil {
			log.Err(err).Msg("failed to read kafka message")
			continue
		}

		// fake event generated by debezium, ignore it
		if len(msg.Value) == 0 {
			continue
		}

		switch msg.Topic {
		case "debezium.chii.bangumi.chii_pms":
			h.handlePM(msg)
		case "debezium.chii.bangumi.chii_notify":
			h.handleNotify(msg)
		}
	}
}
func (h *handler) handlePM(msg kafka.Message) {}

func (h *handler) handleNotify(msg kafka.Message) {

}
