version: "3"

dotenv: [ .env ]

tasks:
  default:
    silent: true
    cmds:
      - task --list-all

  dev:
    sources:
      - main.py
    generates:
      - a-file-not-exists
    cmd: python main.py

  lint:
    - poetry run mypy .
    - poetry run ruff check .
