version: "3"

dotenv: [ .env ]

tasks:
  default:
    silent: true
    cmds:
      - task --list-all

  dev:
    cmd: poetry run watchfiles main.main

  lint:
    - poetry run mypy .
    - poetry run ruff check .
