version: "3"

dotenv: [.env]

tasks:
  default:
    silent: true
    cmds:
      - task --list-all

  build:
    sources:
      - "**/*.go"
    generates:
      - ./dist/app.exe
    cmd: go build -o dist/app.exe

  dev:
    deps:
      - build
    env:
      HTTPS_PROXY: 'http://127.0.0.1:7890'
      HTTP_PROXY: 'http://127.0.0.1:7890'
    cmd: ./dist/app.exe
