name: Release(Docker)

on:
  push:
    tags:
      - v*
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      IMAGE: "ghcr.io/${{ github.repository_owner }}/telegram-bot"

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - uses: trim21/actions/setup-go@master

      - run: go build -o ./dist/telegram-bot
        env:
          CGO_ENABLED: "0"

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=semver,pattern=v{{version}}

            type=ref,event=branch
            type=ref,event=branch,suffix=-{{ sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: Build Final Docker Image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: ./
          provenance: false
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          github-token: ${{ github.token }}
