name: review uv.lock

on:
  pull_request_target:
    branches:
      - master
      - daemon

jobs:
  lock:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: trim21/action-uv-lock-diff-viewer@dist/v0
